# Generated by Django 4.1.3 on 2022-11-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descriptio',
            new_name='description',
        ),
    ]
