# Generated by Django 4.1.3 on 2022-11-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='username',
        ),
    ]
