# Generated by Django 4.1.3 on 2022-11-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_user_like_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folling_by', models.CharField(max_length=20)),
                ('followed_to', models.CharField(max_length=20)),
            ],
        ),
    ]
