# Generated by Django 4.1.3 on 2022-11-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='folling_by',
            new_name='following_by',
        ),
        migrations.RenameField(
            model_name='followers',
            old_name='followed_to',
            new_name='following_to_user',
        ),
    ]
