# Generated by Django 4.1.3 on 2022-11-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_folling_by_followers_following_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
